name: Swift

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
